
spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor

  datasource:
    url: jdbc:h2:mem:testdb
    generate-unique-name: false
    name: testdb
  h2:
    console:
      enabled: true
      path: /h2-console/

server:
  port: 3333

logging:
  level:
    org:
    hibernate:
      stat: debug