

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE) VALUES(10001, 'YASH TAILOR', 'AHMEDABAD', CURRENT_TIMESTAMP);
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE) VALUES(10002, 'Arpit Panchal', 'Dubai', CURRENT_TIMESTAMP);
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE) VALUES(10003, 'Parth', 'AHMEDABAD', CURRENT_TIMESTAMP);